url: https://creatingsapien.github.io
baseurl: ""

# Site settings
title: Mecha Project - Rebuild Robotics
email: gunnar@austincapitaldata.com
description: "rebuiding an indistrial workhorse bot"


# Team names, titles and social links
people:
- name: Gunnar Kleemann
  pic: 1
  position: Lead Maker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Antonio Garica
  pic: 2
  position: Robot Whisperer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Joeseph Ngo
  pic: 3
  position: Robo-Doc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Mysterious contributor
  pic: 4
  position: Master Architect
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
